source 'https://rubygems.org'

gem 'minitest'
gem 'mynyml-redgreen'
gem 'minitest-reporters'

gem 'pry-debugger'

gem 'activerecord', '~> 3.2'
gem 'activerecord-postgresql-adapter'

gem 'sinatra_more'
