MenuItem.create(name: 'Hot Chocolate', price: 2.50)
MenuItem.create(name: 'Milk', price: 2.00)
MenuItem.create(name: 'Bottle water', price: 2.00)
MenuItem.create(name: 'Juice', price: 2.50)
MenuItem.create(name: 'Canned pop', price: 2.00)

RestaurantTable.create(number_of_chairs: 2)
RestaurantTable.create(number_of_chairs: 2)
RestaurantTable.create(number_of_chairs: 2)
RestaurantTable.create(number_of_chairs: 2)
RestaurantTable.create(number_of_chairs: 2)
RestaurantTable.create(number_of_chairs: 2)
RestaurantTable.create(number_of_chairs: 2)
RestaurantTable.create(number_of_chairs: 4)
RestaurantTable.create(number_of_chairs: 2)
RestaurantTable.create(number_of_chairs: 4)
RestaurantTable.create(number_of_chairs: 2)
